[alembic]
script_location = alembic
file_template = %%(year)d_%%(month)02d_%%(day)02d_%%(hour)02d%%(minute)02d-%%(rev)s_%%(slug)s
prepend_sys_path = .
timezone = UTC
sqlalchemy.url = postgresql://postgres:password@localhost:5432/strtos_db

[post_write_hooks]

[logging]
default_levelname = INFO
